name: Build RISC-V runner

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  dotnet_version: 8.0.416

jobs:
  build:
    runs-on: [ self-hosted, Linux, riscv64 ]

    steps:
    - name: Clone repositories
      uses: actions/checkout@v4
      with:
        repository: revyos/runner
        ref: revyos/riscv64_runner_2.330.0
        path: runner

    - name: Download .NET
      run: |
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/dotnet-sdk-${dotnet_version}-linux-riscv64.tar.gz
        mkdir -p $GITHUB_WORKSPACE/packages
        cd $GITHUB_WORKSPACE/packages
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.AspNetCore.App.Runtime.linux-riscv64.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ItemTemplates.8.0.416.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ItemTemplates.8.0.416.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ProjectTemplates.8.0.8.0.416.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ProjectTemplates.8.0.8.0.416.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.Client.ItemTemplates.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.ItemTemplates.8.0.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.ProjectTemplates.8.0.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Host.linux-riscv64.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Host.linux-riscv64.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Runtime.linux-riscv64.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHost.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHost.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostPolicy.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostPolicy.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostResolver.8.0.22.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostResolver.8.0.22.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.ILAsm.8.0.22-ci.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.ILDAsm.8.0.22-ci.nupkg

    - name: Prepare
      run: |
        cd runner
        sed -i "s|/home/ubuntu/packages|$GITHUB_WORKSPACE|" src/NuGet.Config

        mkdir -p _dotnetsdk/${dotnet_version}
        cd _dotnetsdk/${dotnet_version}
        tar -xf $GITHUB_WORKSPACE/dotnet-sdk-${dotnet_version}-linux-riscv64.tar.gz

    - name: Build
      run: |
        cd runner/src
        ./dev.sh layout Release linux-riscv64

    - name: Package
      run: |
        cd runner/src
        ./dev.sh package Release linux-riscv64

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: actions-runner-linux-riscv64
        path: "runner/_package/actions-runner-linux-riscv64-*.tar.gz"

    - name: 'Upload Release'
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: runner/_package/actions-runner-linux-riscv64-*.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
