name: Build RISC-V runner

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  dotnet_version: 8.0.422
  dotnet_sdk_version: 8.0.28

jobs:
  build:
    runs-on: [ self-hosted, Linux, riscv64 ]

    steps:
    - name: Clone repositories
      uses: actions/checkout@v6
      with:
        repository: revyos/runner
        ref: revyos/riscv64_runner_2.336.0
        path: runner

    - name: Download .NET
      run: |
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/dotnet-sdk-${dotnet_version}-linux-riscv64.tar.gz
        mkdir -p $GITHUB_WORKSPACE/packages
        cd $GITHUB_WORKSPACE/packages
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.AspNetCore.App.Runtime.linux-riscv64.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.AspNetCore.App.Runtime.linux-riscv64.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ItemTemplates.${dotnet_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ItemTemplates.${dotnet_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ProjectTemplates.8.0.${dotnet_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Common.ProjectTemplates.8.0.${dotnet_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.Client.ItemTemplates.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.ItemTemplates.8.0.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.DotNet.Web.ProjectTemplates.8.0.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Host.linux-riscv64.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Host.linux-riscv64.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Runtime.linux-riscv64.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/Microsoft.NETCore.App.Runtime.linux-riscv64.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHost.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHost.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostPolicy.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostPolicy.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostResolver.${dotnet_sdk_version}.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.DotNetHostResolver.${dotnet_sdk_version}.symbols.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.ILAsm.${dotnet_sdk_version}-ci.nupkg
        wget https://github.com/revyos/dotnet_cross/releases/download/${dotnet_version}/runtime.linux-riscv64.Microsoft.NETCore.ILDAsm.${dotnet_sdk_version}-ci.nupkg

    - name: Prepare
      run: |
        cd runner
        sed -i "s|/home/ubuntu/packages|$GITHUB_WORKSPACE|" src/NuGet.Config

        mkdir -p _dotnetsdk/${dotnet_version}
        cd _dotnetsdk/${dotnet_version}
        tar -xf $GITHUB_WORKSPACE/dotnet-sdk-${dotnet_version}-linux-riscv64.tar.gz

    - name: Build
      run: |
        cd runner/src
        ./dev.sh layout Release linux-riscv64

    - name: Package
      run: |
        cd runner/src
        ./dev.sh package Release linux-riscv64

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: actions-runner-linux-riscv64
        path: "runner/_package/actions-runner-linux-riscv64-*.tar.gz"

    - name: 'Upload Release'
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: runner/_package/actions-runner-linux-riscv64-*.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
